### ISSUE TITLE
[Feat] 추가 돌진 게이지 및 UI 개편

### ISSUE THREAD

**Issue by lovekku05** [hellun205/princess-of-the-magic-tower#20]
## Descriptions
- 돌진 게이지 UI 개편
- 특정 적 처치 시 추가 돌진 게이지 충전
- 추가 돌진 게이지가 충전되는 적들 설정: 더미 색 차별화
- 일반 게이지보다 추가 게이지가 더 먼저 사용 됨

## To do
- [x] #23
- [x] #24
- [ ] 해당 몹 구별 및 차별화

## Deadline
- 2023-09-05 회의 전

**Comment by vczyx** [comment]
돌진 게이지 UI 디자인 초안
![image](https://github.com/hellun205/princess-of-the-magic-tower/assets/74102978/6ed233a5-7fd1-425d-855e-4045d6c7c75a)
